## To modify by developper(s) of the plugin

[plugin-info]
SHORT_PLUGIN_NAME = 'oceaninsight'  #for instance daqmx
package-url = 'https://github.com/PyMoDAQ/pymodaq_plugins_oceaninsight' #to modify
description = 'Set of PyMoDAQ plugins for OceanInsight (OceanOptics) spectrometers'

author = 'SÃ©bastien Weber'
author-email = 'sebastien.weber@cemes.fr'
license = 'MIT'

[plugin-install]
#packages required for your plugin:
packages-required = ['pythonnet','seabreeze']
##